---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is success
  retries: 5
  delay: 2
  with_items: "{{ phpfpm_exporter_dependencies }}"

- name: Create the phpfpm_exporter group
  group:
    name: "{{ phpfpm_exporter_system_group }}"
    state: present
    system: true
  when: phpfpm_exporter_system_group != "root" and phpfpm_exporter_manage_system_user_group

- name: Create the phpfpm_exporter user
  user:
    name: "{{ phpfpm_exporter_system_user }}"
    group: "{{ phpfpm_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: phpfpm_exporter_system_user != "root" and phpfpm_exporter_manage_system_user_group

- name: Download phpfpm_exporter binary
  get_url:
    url: "https://github.com/hipages/php-fpm_exporter/releases/download/v{{ phpfpm_exporter_version }}/php-fpm_exporter_{{ phpfpm_exporter_version }}_linux_{{ go_arch }}"
    dest: "/usr/local/bin/phpfpm_exporter"
    checksum: "sha256:{{ phpfpm_exporter_checksum }}"
    mode: 0755
    owner: root
    group: root
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false
  notify: restart phpfpm_exporter
